server:
  port: 8888

spring:
  application:
    name: ConfigServer
  profiles: 
    active: native
  cloud:
    config:
      server:
        native :
          searchLocations : file:D:/reos/microservices/config/
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/          
     
